services:
  backend:
    build:
      context: ./TrainingPointApp
    container_name: springmvc
    ports:
      - "8080:8080"
    depends_on:
      - database
    restart: always
  frontend:
    build:
      context: ./trainingpointweb
    container_name: reactjs
    ports:
      - "5679:5679"
    depends_on:
      - backend
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    env_file:
      - ./trainingpointweb/.env
  database:
    image: mysql:8.0.39
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      - MYSQL_DATABASE=trainingpointdb
      - MYSQL_ROOT_PASSWORD=Admin@123
    volumes:
      - ./db:/var/lib/mysql
      - ./scripts/:/docker-entrypoint-initdb.d/
    restart: always
  # nginx:
  #   image: nginx
  #   container_name: nginx_docker
  #   ports:
  #     - 5679:5679
  #   depends_on:
  #     - frontend
  #     - backend
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  #   restart: always
volumes:
  db:
  nginx:
